<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WordsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('words')->insert(
            [
                ['name_en' => 'Monday', 'name_pl' => 'poniedziałek', 'subcategory_id' => 1],
                ['name_en' => 'Tuesday', 'name_pl' => 'wtorek', 'subcategory_id' => 1],
                ['name_en' => 'Wednesday', 'name_pl' => 'środa', 'subcategory_id' => 1],
                ['name_en' => 'Thursday', 'name_pl' => 'czwartek', 'subcategory_id' => 1],
                ['name_en' => 'Friday', 'name_pl' => 'piątek', 'subcategory_id' => 1],
                ['name_en' => 'Saturday', 'name_pl' => 'sobota', 'subcategory_id' => 1],
                ['name_en' => 'Sunday', 'name_pl' => 'niedziela', 'subcategory_id' => 1],
                ['name_en' => 'blue', 'name_pl' => 'niebieski', 'subcategory_id' => 2],
                ['name_en' => 'red', 'name_pl' => 'czerwony', 'subcategory_id' => 2],
                ['name_en' => 'green', 'name_pl' => 'zielony', 'subcategory_id' => 2],
                ['name_en' => 'yellow', 'name_pl' => 'żółty', 'subcategory_id' => 2],
                ['name_en' => 'white', 'name_pl' => 'biały', 'subcategory_id' => 2],
                ['name_en' => 'black', 'name_pl' => 'czarny', 'subcategory_id' => 2],
                ['name_en' => 'orange', 'name_pl' => 'pomarańczowy', 'subcategory_id' => 2],
                ['name_en' => 'pink', 'name_pl' => 'różowy', 'subcategory_id' => 2],
                ['name_en' => 'purple', 'name_pl' => 'fioletowy', 'subcategory_id' => 2],
                ['name_en' => 'brown', 'name_pl' => 'brązowy', 'subcategory_id' => 2],
                ['name_en' => 'grey', 'name_pl' => 'szary', 'subcategory_id' => 2],
                ['name_en' => 'silver', 'name_pl' => 'srebny', 'subcategory_id' => 2],
                ['name_en' => 'golden', 'name_pl' => 'złoty', 'subcategory_id' => 2],
                ['name_en' => 'light', 'name_pl' => 'jasny', 'subcategory_id' => 2],
                ['name_en' => 'dark', 'name_pl' => 'ciemny', 'subcategory_id' => 2],
                ['name_en' => 'one', 'name_pl' => 'jeden', 'subcategory_id' => 3],
                ['name_en' => 'two', 'name_pl' => 'dwa', 'subcategory_id' => 3],
                ['name_en' => 'three', 'name_pl' => 'trzy', 'subcategory_id' => 3],
                ['name_en' => 'four', 'name_pl' => 'cztery', 'subcategory_id' => 3],
                ['name_en' => 'five', 'name_pl' => 'pięć', 'subcategory_id' => 3],
                ['name_en' => 'six', 'name_pl' => 'sześć', 'subcategory_id' => 3],
                ['name_en' => 'seven', 'name_pl' => 'siedem', 'subcategory_id' => 3],
                ['name_en' => 'eight', 'name_pl' => 'osiem', 'subcategory_id' => 3],
                ['name_en' => 'nine', 'name_pl' => 'dziewięć', 'subcategory_id' => 3],
                ['name_en' => 'ten', 'name_pl' => 'dziesięć', 'subcategory_id' => 3],
                ['name_en' => 'eleven', 'name_pl' => 'jedenaście', 'subcategory_id' => 3],
                ['name_en' => 'twelve', 'name_pl' => 'dwanaście', 'subcategory_id' => 3],
                ['name_en' => 'thirteen', 'name_pl' => 'trzynaście', 'subcategory_id' => 3],
                ['name_en' => 'fourteen', 'name_pl' => 'czternaście', 'subcategory_id' => 3],
                ['name_en' => 'fifteen', 'name_pl' => 'piętnaście', 'subcategory_id' => 3],
                ['name_en' => 'sixteen', 'name_pl' => 'szesnaście', 'subcategory_id' => 3],
                ['name_en' => 'seventeen', 'name_pl' => 'siedemnaście', 'subcategory_id' => 3],
                ['name_en' => 'eighteen', 'name_pl' => 'osiemnaście', 'subcategory_id' => 3],
                ['name_en' => 'nineteen', 'name_pl' => 'dziewiętnaście', 'subcategory_id' => 3],
                ['name_en' => 'twenty', 'name_pl' => 'dwadzieścia', 'subcategory_id' => 3],
                ['name_en' => 'thirty', 'name_pl' => 'trzydzieści', 'subcategory_id' => 3],
                ['name_en' => 'hundred', 'name_pl' => 'sto', 'subcategory_id' => 3],
                ['name_en' => 'thousand', 'name_pl' => 'tysiąc', 'subcategory_id' => 3],
                ['name_en' => 'January', 'name_pl' => 'styczeń', 'subcategory_id' => 4],
                ['name_en' => 'February', 'name_pl' => 'luty', 'subcategory_id' => 4],
                ['name_en' => 'March', 'name_pl' => 'marzec', 'subcategory_id' => 4],
                ['name_en' => 'April', 'name_pl' => 'kwiecień', 'subcategory_id' => 4],
                ['name_en' => 'May', 'name_pl' => 'maj', 'subcategory_id' => 4],
                ['name_en' => 'June', 'name_pl' => 'czerwiec', 'subcategory_id' => 4],
                ['name_en' => 'July', 'name_pl' => 'lipiec', 'subcategory_id' => 4],
                ['name_en' => 'August', 'name_pl' => 'sierpień', 'subcategory_id' => 4],
                ['name_en' => 'September', 'name_pl' => 'wrzesień', 'subcategory_id' => 4],
                ['name_en' => 'October', 'name_pl' => 'październik', 'subcategory_id' => 4],
                ['name_en' => 'December', 'name_pl' => 'listopad', 'subcategory_id' => 4],
                ['name_en' => 'apple', 'name_pl' => 'jabłko', 'subcategory_id' => 5],
                ['name_en' => 'apricot', 'name_pl' => 'morela', 'subcategory_id' => 5],
                ['name_en' => 'avocado', 'name_pl' => 'awokado', 'subcategory_id' => 5],
                ['name_en' => 'cherry', 'name_pl' => 'wiśnia', 'subcategory_id' => 5],
                ['name_en' => 'pear', 'name_pl' => 'gruszka', 'subcategory_id' => 5],
                ['name_en' => 'banana', 'name_pl' => 'banan', 'subcategory_id' => 5],
                ['name_en' => 'orange', 'name_pl' => 'pomarańcza', 'subcategory_id' => 5],
                ['name_en' => 'strawberry', 'name_pl' => 'truskawka', 'subcategory_id' => 5],
                ['name_en' => 'raspberry', 'name_pl' => 'malina', 'subcategory_id' => 5],
                ['name_en' => 'grapes', 'name_pl' => 'winogrona', 'subcategory_id' => 5],
                ['name_en' => 'lemon', 'name_pl' => 'cytryna', 'subcategory_id' => 5],
                ['name_en' => 'lime', 'name_pl' => 'limonka', 'subcategory_id' => 5],
                ['name_en' => 'peach', 'name_pl' => 'brzoskwinia', 'subcategory_id' => 5],
                ['name_en' => 'pineapple', 'name_pl' => 'ananas', 'subcategory_id' => 5],
                ['name_en' => 'plum', 'name_pl' => 'śliwka', 'subcategory_id' => 5],
                ['name_en' => 'pomegranate', 'name_pl' => 'granat', 'subcategory_id' => 5],
                ['name_en' => 'sunflower', 'name_pl' => 'słonecznik', 'subcategory_id' => 5],
                ['name_en' => 'watermelon', 'name_pl' => 'arbuz', 'subcategory_id' => 5],
                ['name_en' => 'carrot', 'name_pl' => 'markewka', 'subcategory_id' => 6],
                ['name_en' => 'cucumber', 'name_pl' => 'ogórek', 'subcategory_id' => 6],
                ['name_en' => 'onion', 'name_pl' => 'cebula', 'subcategory_id' => 6],
                ['name_en' => 'tomato', 'name_pl' => 'pomidor', 'subcategory_id' => 6],
                ['name_en' => 'cabbage', 'name_pl' => 'kapusta', 'subcategory_id' => 6],
                ['name_en' => 'lettuce', 'name_pl' => 'sałata', 'subcategory_id' => 6],
                ['name_en' => 'pepper', 'name_pl' => 'papryka', 'subcategory_id' => 6],
                ['name_en' => 'eggplant', 'name_pl' => 'bakłażan', 'subcategory_id' => 6],
                ['name_en' => 'pumpkin', 'name_pl' => 'dynia', 'subcategory_id' => 6],
                ['name_en' => 'beet', 'name_pl' => 'burak', 'subcategory_id' => 6],
                ['name_en' => 'asparagus', 'name_pl' => 'szparagi', 'subcategory_id' => 6],
                ['name_en' => 'corn', 'name_pl' => 'kukurydza', 'subcategory_id' => 6],
                ['name_en' => 'broccoli', 'name_pl' => 'brokuły', 'subcategory_id' => 6],
                ['name_en' => 'garlic', 'name_pl' => 'czosnek', 'subcategory_id' => 6],
                ['name_en' => 'potato', 'name_pl' => 'ziemniak', 'subcategory_id' => 6],
                ['name_en' => 'peas', 'name_pl' => 'groszek', 'subcategory_id' => 6],
                ['name_en' => 'mushroom', 'name_pl' => 'grzyb', 'subcategory_id' => 6],
                ['name_en' => 'lamb', 'name_pl' => 'baranina', 'subcategory_id' => 7],
                ['name_en' => 'beef', 'name_pl' => 'wołowina', 'subcategory_id' => 7],
                ['name_en' => 'pork', 'name_pl' => 'wieprzowina', 'subcategory_id' => 7],
                ['name_en' => 'chicken', 'name_pl' => 'kurczak', 'subcategory_id' => 7],
                ['name_en' => 'turkey', 'name_pl' => 'indyk', 'subcategory_id' => 7],
                ['name_en' => 'veal', 'name_pl' => 'cielęcinka', 'subcategory_id' => 7],
                ['name_en' => 'duck', 'name_pl' => 'kaczka', 'subcategory_id' => 7],
                ['name_en' => 'sausage', 'name_pl' => 'kiełbasa', 'subcategory_id' => 7],
                ['name_en' => 'bacon', 'name_pl' => 'bekon/boczek', 'subcategory_id' => 7],
                ['name_en' => 'ham', 'name_pl' => 'szynka', 'subcategory_id' => 7],
                ['name_en' => 'poultry', 'name_pl' => 'drób', 'subcategory_id' => 7],
                ['name_en' => 'goose', 'name_pl' => 'gęś', 'subcategory_id' => 7],
                ['name_en' => 'minced meat', 'name_pl' => 'mięso mielone', 'subcategory_id' => 7],
                ['name_en' => 'steak', 'name_pl' => 'stek', 'subcategory_id' => 7],
                ['name_en' => 'venison', 'name_pl' => 'dziczyzna', 'subcategory_id' => 7],
                ['name_en' => 'basketball', 'name_pl' => 'koszykówka', 'subcategory_id' => 8],
                ['name_en' => 'climbing', 'name_pl' => 'wspinaczka', 'subcategory_id' => 8],
                ['name_en' => 'athletics', 'name_pl' => 'lekkoatletyka', 'subcategory_id' => 8],
                ['name_en' => 'chess', 'name_pl' => 'szachy', 'subcategory_id' => 8],
                ['name_en' => 'swimming', 'name_pl' => 'pływanie', 'subcategory_id' => 8],
                ['name_en' => 'sailing', 'name_pl' => 'żeglarstwo', 'subcategory_id' => 8],
                ['name_en' => 'cycling', 'name_pl' => 'kolarstwo', 'subcategory_id' => 8],
                ['name_en' => 'billiards', 'name_pl' => 'bilard', 'subcategory_id' => 8],
                ['name_en' => 'bowling', 'name_pl' => 'kręgle', 'subcategory_id' => 8],
                ['name_en' => 'darts', 'name_pl' => 'rzutki', 'subcategory_id' => 8],
                ['name_en' => 'archery', 'name_pl' => 'łucznictwo', 'subcategory_id' => 8],
                ['name_en' => 'biathlon', 'name_pl' => 'biathlon', 'subcategory_id' => 8],
                ['name_en' => 'ski jumping', 'name_pl' => 'skoki narciarskie', 'subcategory_id' => 8],
                ['name_en' => 'golf', 'name_pl' => 'golf', 'subcategory_id' => 8],
                ['name_en' => 'tennis', 'name_pl' => 'tenis', 'subcategory_id' => 8],
                ['name_en' => 'table tennis', 'name_pl' => 'tenis stołowy', 'subcategory_id' => 8],
                ['name_en' => 'football', 'name_pl' => 'piłka nożna', 'subcategory_id' => 8],
                ['name_en' => 'motorsport', 'name_pl' => 'sporty motorowe', 'subcategory_id' => 8],
                ['name_en' => 'parachuting', 'name_pl' => 'spadochroniarstwo', 'subcategory_id' => 8],
                ['name_en' => 'hockey', 'name_pl' => 'hokej', 'subcategory_id' => 8],
                ['name_en' => 'handball', 'name_pl' => 'piłka ręczna', 'subcategory_id' => 8],
                ['name_en' => 'volleyball', 'name_pl' => 'siatkówka', 'subcategory_id' => 8],
                ['name_en' => 'football pitch', 'name_pl' => 'boisko do piłki nożnej', 'subcategory_id' => 9],
                ['name_en' => 'penalty area', 'name_pl' => 'pole karne', 'subcategory_id' => 9],
                ['name_en' => 'penalty', 'name_pl' => 'rzut karny', 'subcategory_id' => 9],
                ['name_en' => 'free kick', 'name_pl' => 'rzut wolny', 'subcategory_id' => 9],
                ['name_en' => 'corner ', 'name_pl' => 'rzut rożny', 'subcategory_id' => 9],
                ['name_en' => 'foul', 'name_pl' => 'faul', 'subcategory_id' => 9],
                ['name_en' => 'goal', 'name_pl' => 'bramka/gol', 'subcategory_id' => 9],
                ['name_en' => 'goalkeeper', 'name_pl' => 'bramkarz', 'subcategory_id' => 9],
                ['name_en' => 'defender', 'name_pl' => 'obrońca', 'subcategory_id' => 9],
                ['name_en' => 'midfielder', 'name_pl' => 'pomocnik', 'subcategory_id' => 9],
                ['name_en' => 'attacker', 'name_pl' => 'napastnik', 'subcategory_id' => 9],
                ['name_en' => 'captain', 'name_pl' => 'kapitan', 'subcategory_id' => 9],
                ['name_en' => 'coach', 'name_pl' => 'trener', 'subcategory_id' => 9],
                ['name_en' => 'referee', 'name_pl' => 'sędzia', 'subcategory_id' => 9],
                ['name_en' => 'score a goal', 'name_pl' => 'strzelić bramkę', 'subcategory_id' => 9],
                ['name_en' => 'goal scorer', 'name_pl' => 'strzelec bramki', 'subcategory_id' => 9],
                ['name_en' => 'half-time', 'name_pl' => 'przerwa', 'subcategory_id' => 9],
                ['name_en' => 'extra time', 'name_pl' => 'dogrywka', 'subcategory_id' => 9],
                ['name_en' => 'stadium', 'name_pl' => 'stadion', 'subcategory_id' => 9],
                ['name_en' => 'top scorer', 'name_pl' => 'król strzelców', 'subcategory_id' => 9],
                ['name_en' => 'post', 'name_pl' => 'słupek', 'subcategory_id' => 9],
                ['name_en' => 'own goal', 'name_pl' => 'bramka samobójcza', 'subcategory_id' => 9],
                ['name_en' => 'opponent', 'name_pl' => 'przeciwnik', 'subcategory_id' => 9],
                ['name_en' => 'offside', 'name_pl' => 'spalony', 'subcategory_id' => 9],
                ['name_en' => 'play-off', 'name_pl' => 'baraż', 'subcategory_id' => 9],
                ['name_en' => 'helmet', 'name_pl' => 'kask', 'subcategory_id' => 10],
                ['name_en' => 'tire', 'name_pl' => 'opona', 'subcategory_id' => 10],
                ['name_en' => 'brakes', 'name_pl' => 'hamulce', 'subcategory_id' => 10],
                ['name_en' => 'car body', 'name_pl' => 'karoseria', 'subcategory_id' => 10],
                ['name_en' => 'roll cage', 'name_pl' => 'klatka bezpieczeństwa', 'subcategory_id' => 10],
                ['name_en' => 'engine', 'name_pl' => 'silnik', 'subcategory_id' => 10],
                ['name_en' => 'spoiler', 'name_pl' => 'spojler', 'subcategory_id' => 10],
                ['name_en' => 'race car', 'name_pl' => 'samochód wyścigowy', 'subcategory_id' => 10],
                ['name_en' => 'safety car', 'name_pl' => 'samochód bezpieczeństwa', 'subcategory_id' => 10],
                ['name_en' => 'race', 'name_pl' => 'wyścig', 'subcategory_id' => 10],
                ['name_en' => 'qualifications', 'name_pl' => 'kwalifikacje', 'subcategory_id' => 10],
                ['name_en' => 'rally', 'name_pl' => 'rajd', 'subcategory_id' => 10],
                ['name_en' => 'off-road', 'name_pl' => 'wyścig terenowy', 'subcategory_id' => 10],
                ['name_en' => 'racetrack', 'name_pl' => 'tor wyścigowy', 'subcategory_id' => 10],
                ['name_en' => 'special stage', 'name_pl' => 'odcinek specjalny', 'subcategory_id' => 10],
                ['name_en' => 'overtake', 'name_pl' => 'wyprzedzać', 'subcategory_id' => 10]
            ]
        );
    }
}
