<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WordsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('words')->insert(
            [
                ['name_en' => 'Monday', 'name_pl' => 'poniedziałek', 'subcategory_id' => 1],
                ['name_en' => 'Tuesday', 'name_pl' => 'wtorek', 'subcategory_id' => 1],
                ['name_en' => 'Wednesday', 'name_pl' => 'środa', 'subcategory_id' => 1],
                ['name_en' => 'Thursday', 'name_pl' => 'czwartek', 'subcategory_id' => 1],
                ['name_en' => 'Friday', 'name_pl' => 'piątek', 'subcategory_id' => 1],
                ['name_en' => 'Saturday', 'name_pl' => 'sobota', 'subcategory_id' => 1],
                ['name_en' => 'Sunday', 'name_pl' => 'niedziela', 'subcategory_id' => 1],
                ['name_en' => 'blue', 'name_pl' => 'niebieski', 'subcategory_id' => 2],
                ['name_en' => 'red', 'name_pl' => 'czerwony', 'subcategory_id' => 2],
                ['name_en' => 'green', 'name_pl' => 'zielony', 'subcategory_id' => 2],
                ['name_en' => 'yellow', 'name_pl' => 'żółty', 'subcategory_id' => 2],
                ['name_en' => 'white', 'name_pl' => 'biały', 'subcategory_id' => 2],
                ['name_en' => 'black', 'name_pl' => 'czarny', 'subcategory_id' => 2],
                ['name_en' => 'orange', 'name_pl' => 'pomarańczowy', 'subcategory_id' => 2],
                ['name_en' => 'pink', 'name_pl' => 'różowy', 'subcategory_id' => 2],
                ['name_en' => 'purple', 'name_pl' => 'fioletowy', 'subcategory_id' => 2],
                ['name_en' => 'brown', 'name_pl' => 'brązowy', 'subcategory_id' => 2],
                ['name_en' => 'grey', 'name_pl' => 'szary', 'subcategory_id' => 2],
                ['name_en' => 'silver', 'name_pl' => 'srebny', 'subcategory_id' => 2],
                ['name_en' => 'golden', 'name_pl' => 'złoty', 'subcategory_id' => 2],
                ['name_en' => 'light', 'name_pl' => 'jasny', 'subcategory_id' => 2],
                ['name_en' => 'dark', 'name_pl' => 'ciemny', 'subcategory_id' => 2],
                ['name_en' => 'one', 'name_pl' => 'jeden', 'subcategory_id' => 3],
                ['name_en' => 'two', 'name_pl' => 'dwa', 'subcategory_id' => 3],
                ['name_en' => 'three', 'name_pl' => 'trzy', 'subcategory_id' => 3],
                ['name_en' => 'four', 'name_pl' => 'cztery', 'subcategory_id' => 3],
                ['name_en' => 'five', 'name_pl' => 'pięć', 'subcategory_id' => 3],
                ['name_en' => 'six', 'name_pl' => 'sześć', 'subcategory_id' => 3],
                ['name_en' => 'seven', 'name_pl' => 'siedem', 'subcategory_id' => 3],
                ['name_en' => 'eight', 'name_pl' => 'osiem', 'subcategory_id' => 3],
                ['name_en' => 'nine', 'name_pl' => 'dziewięć', 'subcategory_id' => 3],
                ['name_en' => 'ten', 'name_pl' => 'dziesięć', 'subcategory_id' => 3],
                ['name_en' => 'eleven', 'name_pl' => 'jedenaście', 'subcategory_id' => 3],
                ['name_en' => 'twelve', 'name_pl' => 'dwanaście', 'subcategory_id' => 3],
                ['name_en' => 'thirteen', 'name_pl' => 'trzynaście', 'subcategory_id' => 3],
                ['name_en' => 'fourteen', 'name_pl' => 'czternaście', 'subcategory_id' => 3],
                ['name_en' => 'fifteen', 'name_pl' => 'piętnaście', 'subcategory_id' => 3],
                ['name_en' => 'sixteen', 'name_pl' => 'szesnaście', 'subcategory_id' => 3],
                ['name_en' => 'seventeen', 'name_pl' => 'siedemnaście', 'subcategory_id' => 3],
                ['name_en' => 'eighteen', 'name_pl' => 'osiemnaście', 'subcategory_id' => 3],
                ['name_en' => 'nineteen', 'name_pl' => 'dziewiętnaście', 'subcategory_id' => 3],
                ['name_en' => 'twenty', 'name_pl' => 'dwadzieścia', 'subcategory_id' => 3],
                ['name_en' => 'thirty', 'name_pl' => 'trzydzieści', 'subcategory_id' => 3],
                ['name_en' => 'hundred', 'name_pl' => 'sto', 'subcategory_id' => 3],
                ['name_en' => 'thousand', 'name_pl' => 'tysiąc', 'subcategory_id' => 3],
                ['name_en' => 'January', 'name_pl' => 'styczeń', 'subcategory_id' => 4],
                ['name_en' => 'February', 'name_pl' => 'luty', 'subcategory_id' => 4],
                ['name_en' => 'March', 'name_pl' => 'marzec', 'subcategory_id' => 4],
                ['name_en' => 'April', 'name_pl' => 'kwiecień', 'subcategory_id' => 4],
                ['name_en' => 'May', 'name_pl' => 'maj', 'subcategory_id' => 4],
                ['name_en' => 'June', 'name_pl' => 'czerwiec', 'subcategory_id' => 4],
                ['name_en' => 'July', 'name_pl' => 'lipiec', 'subcategory_id' => 4],
                ['name_en' => 'August', 'name_pl' => 'sierpień', 'subcategory_id' => 4],
                ['name_en' => 'September', 'name_pl' => 'wrzesień', 'subcategory_id' => 4],
                ['name_en' => 'October', 'name_pl' => 'październik', 'subcategory_id' => 4],
                ['name_en' => 'November', 'name_pl' => 'listopad', 'subcategory_id' => 4],
                ['name_en' => 'December', 'name_pl' => 'grudzień', 'subcategory_id' => 4],
                ['name_en' => 'apple', 'name_pl' => 'jabłko', 'subcategory_id' => 5],
                ['name_en' => 'apricot', 'name_pl' => 'morela', 'subcategory_id' => 5],
                ['name_en' => 'avocado', 'name_pl' => 'awokado', 'subcategory_id' => 5],
                ['name_en' => 'cherry', 'name_pl' => 'wiśnia', 'subcategory_id' => 5],
                ['name_en' => 'pear', 'name_pl' => 'gruszka', 'subcategory_id' => 5],
                ['name_en' => 'banana', 'name_pl' => 'banan', 'subcategory_id' => 5],
                ['name_en' => 'orange', 'name_pl' => 'pomarańcza', 'subcategory_id' => 5],
                ['name_en' => 'strawberry', 'name_pl' => 'truskawka', 'subcategory_id' => 5],
                ['name_en' => 'raspberry', 'name_pl' => 'malina', 'subcategory_id' => 5],
                ['name_en' => 'grapes', 'name_pl' => 'winogrona', 'subcategory_id' => 5],
                ['name_en' => 'lemon', 'name_pl' => 'cytryna', 'subcategory_id' => 5],
                ['name_en' => 'lime', 'name_pl' => 'limonka', 'subcategory_id' => 5],
                ['name_en' => 'peach', 'name_pl' => 'brzoskwinia', 'subcategory_id' => 5],
                ['name_en' => 'pineapple', 'name_pl' => 'ananas', 'subcategory_id' => 5],
                ['name_en' => 'plum', 'name_pl' => 'śliwka', 'subcategory_id' => 5],
                ['name_en' => 'pomegranate', 'name_pl' => 'granat', 'subcategory_id' => 5],
                ['name_en' => 'sunflower', 'name_pl' => 'słonecznik', 'subcategory_id' => 5],
                ['name_en' => 'watermelon', 'name_pl' => 'arbuz', 'subcategory_id' => 5],
                ['name_en' => 'carrot', 'name_pl' => 'markewka', 'subcategory_id' => 6],
                ['name_en' => 'cucumber', 'name_pl' => 'ogórek', 'subcategory_id' => 6],
                ['name_en' => 'onion', 'name_pl' => 'cebula', 'subcategory_id' => 6],
                ['name_en' => 'tomato', 'name_pl' => 'pomidor', 'subcategory_id' => 6],
                ['name_en' => 'cabbage', 'name_pl' => 'kapusta', 'subcategory_id' => 6],
                ['name_en' => 'lettuce', 'name_pl' => 'sałata', 'subcategory_id' => 6],
                ['name_en' => 'pepper', 'name_pl' => 'papryka', 'subcategory_id' => 6],
                ['name_en' => 'eggplant', 'name_pl' => 'bakłażan', 'subcategory_id' => 6],
                ['name_en' => 'pumpkin', 'name_pl' => 'dynia', 'subcategory_id' => 6],
                ['name_en' => 'beet', 'name_pl' => 'burak', 'subcategory_id' => 6],
                ['name_en' => 'asparagus', 'name_pl' => 'szparagi', 'subcategory_id' => 6],
                ['name_en' => 'corn', 'name_pl' => 'kukurydza', 'subcategory_id' => 6],
                ['name_en' => 'broccoli', 'name_pl' => 'brokuły', 'subcategory_id' => 6],
                ['name_en' => 'garlic', 'name_pl' => 'czosnek', 'subcategory_id' => 6],
                ['name_en' => 'potato', 'name_pl' => 'ziemniak', 'subcategory_id' => 6],
                ['name_en' => 'peas', 'name_pl' => 'groszek', 'subcategory_id' => 6],
                ['name_en' => 'mushroom', 'name_pl' => 'grzyb', 'subcategory_id' => 6],
                ['name_en' => 'lamb', 'name_pl' => 'baranina', 'subcategory_id' => 7],
                ['name_en' => 'beef', 'name_pl' => 'wołowina', 'subcategory_id' => 7],
                ['name_en' => 'pork', 'name_pl' => 'wieprzowina', 'subcategory_id' => 7],
                ['name_en' => 'chicken', 'name_pl' => 'kurczak', 'subcategory_id' => 7],
                ['name_en' => 'turkey', 'name_pl' => 'indyk', 'subcategory_id' => 7],
                ['name_en' => 'veal', 'name_pl' => 'cielęcinka', 'subcategory_id' => 7],
                ['name_en' => 'duck', 'name_pl' => 'kaczka', 'subcategory_id' => 7],
                ['name_en' => 'sausage', 'name_pl' => 'kiełbasa', 'subcategory_id' => 7],
                ['name_en' => 'bacon', 'name_pl' => 'bekon/boczek', 'subcategory_id' => 7],
                ['name_en' => 'ham', 'name_pl' => 'szynka', 'subcategory_id' => 7],
                ['name_en' => 'poultry', 'name_pl' => 'drób', 'subcategory_id' => 7],
                ['name_en' => 'goose', 'name_pl' => 'gęś', 'subcategory_id' => 7],
                ['name_en' => 'minced meat', 'name_pl' => 'mięso mielone', 'subcategory_id' => 7],
                ['name_en' => 'steak', 'name_pl' => 'stek', 'subcategory_id' => 7],
                ['name_en' => 'venison', 'name_pl' => 'dziczyzna', 'subcategory_id' => 7],
                ['name_en' => 'basketball', 'name_pl' => 'koszykówka', 'subcategory_id' => 8],
                ['name_en' => 'climbing', 'name_pl' => 'wspinaczka', 'subcategory_id' => 8],
                ['name_en' => 'athletics', 'name_pl' => 'lekkoatletyka', 'subcategory_id' => 8],
                ['name_en' => 'chess', 'name_pl' => 'szachy', 'subcategory_id' => 8],
                ['name_en' => 'swimming', 'name_pl' => 'pływanie', 'subcategory_id' => 8],
                ['name_en' => 'sailing', 'name_pl' => 'żeglarstwo', 'subcategory_id' => 8],
                ['name_en' => 'cycling', 'name_pl' => 'kolarstwo', 'subcategory_id' => 8],
                ['name_en' => 'billiards', 'name_pl' => 'bilard', 'subcategory_id' => 8],
                ['name_en' => 'bowling', 'name_pl' => 'kręgle', 'subcategory_id' => 8],
                ['name_en' => 'darts', 'name_pl' => 'rzutki', 'subcategory_id' => 8],
                ['name_en' => 'archery', 'name_pl' => 'łucznictwo', 'subcategory_id' => 8],
                ['name_en' => 'biathlon', 'name_pl' => 'biathlon', 'subcategory_id' => 8],
                ['name_en' => 'ski jumping', 'name_pl' => 'skoki narciarskie', 'subcategory_id' => 8],
                ['name_en' => 'golf', 'name_pl' => 'golf', 'subcategory_id' => 8],
                ['name_en' => 'tennis', 'name_pl' => 'tenis', 'subcategory_id' => 8],
                ['name_en' => 'table tennis', 'name_pl' => 'tenis stołowy', 'subcategory_id' => 8],
                ['name_en' => 'football', 'name_pl' => 'piłka nożna', 'subcategory_id' => 8],
                ['name_en' => 'motorsport', 'name_pl' => 'sporty motorowe', 'subcategory_id' => 8],
                ['name_en' => 'parachuting', 'name_pl' => 'spadochroniarstwo', 'subcategory_id' => 8],
                ['name_en' => 'hockey', 'name_pl' => 'hokej', 'subcategory_id' => 8],
                ['name_en' => 'handball', 'name_pl' => 'piłka ręczna', 'subcategory_id' => 8],
                ['name_en' => 'volleyball', 'name_pl' => 'siatkówka', 'subcategory_id' => 8],
                ['name_en' => 'football pitch', 'name_pl' => 'boisko do piłki nożnej', 'subcategory_id' => 9],
                ['name_en' => 'penalty area', 'name_pl' => 'pole karne', 'subcategory_id' => 9],
                ['name_en' => 'penalty', 'name_pl' => 'rzut karny', 'subcategory_id' => 9],
                ['name_en' => 'free kick', 'name_pl' => 'rzut wolny', 'subcategory_id' => 9],
                ['name_en' => 'corner ', 'name_pl' => 'rzut rożny', 'subcategory_id' => 9],
                ['name_en' => 'foul', 'name_pl' => 'faul', 'subcategory_id' => 9],
                ['name_en' => 'goal', 'name_pl' => 'bramka/gol', 'subcategory_id' => 9],
                ['name_en' => 'goalkeeper', 'name_pl' => 'bramkarz', 'subcategory_id' => 9],
                ['name_en' => 'defender', 'name_pl' => 'obrońca', 'subcategory_id' => 9],
                ['name_en' => 'midfielder', 'name_pl' => 'pomocnik', 'subcategory_id' => 9],
                ['name_en' => 'attacker', 'name_pl' => 'napastnik', 'subcategory_id' => 9],
                ['name_en' => 'captain', 'name_pl' => 'kapitan', 'subcategory_id' => 9],
                ['name_en' => 'coach', 'name_pl' => 'trener', 'subcategory_id' => 9],
                ['name_en' => 'referee', 'name_pl' => 'sędzia', 'subcategory_id' => 9],
                ['name_en' => 'score a goal', 'name_pl' => 'strzelić bramkę', 'subcategory_id' => 9],
                ['name_en' => 'goal scorer', 'name_pl' => 'strzelec bramki', 'subcategory_id' => 9],
                ['name_en' => 'half-time', 'name_pl' => 'przerwa', 'subcategory_id' => 9],
                ['name_en' => 'extra time', 'name_pl' => 'dogrywka', 'subcategory_id' => 9],
                ['name_en' => 'stadium', 'name_pl' => 'stadion', 'subcategory_id' => 9],
                ['name_en' => 'top scorer', 'name_pl' => 'król strzelców', 'subcategory_id' => 9],
                ['name_en' => 'post', 'name_pl' => 'słupek', 'subcategory_id' => 9],
                ['name_en' => 'own goal', 'name_pl' => 'bramka samobójcza', 'subcategory_id' => 9],
                ['name_en' => 'opponent', 'name_pl' => 'przeciwnik', 'subcategory_id' => 9],
                ['name_en' => 'offside', 'name_pl' => 'spalony', 'subcategory_id' => 9],
                ['name_en' => 'play-off', 'name_pl' => 'baraż', 'subcategory_id' => 9],
                ['name_en' => 'helmet', 'name_pl' => 'kask', 'subcategory_id' => 10],
                ['name_en' => 'tire', 'name_pl' => 'opona', 'subcategory_id' => 10],
                ['name_en' => 'brakes', 'name_pl' => 'hamulce', 'subcategory_id' => 10],
                ['name_en' => 'car body', 'name_pl' => 'karoseria', 'subcategory_id' => 10],
                ['name_en' => 'roll cage', 'name_pl' => 'klatka bezpieczeństwa', 'subcategory_id' => 10],
                ['name_en' => 'engine', 'name_pl' => 'silnik', 'subcategory_id' => 10],
                ['name_en' => 'spoiler', 'name_pl' => 'spojler', 'subcategory_id' => 10],
                ['name_en' => 'race car', 'name_pl' => 'samochód wyścigowy', 'subcategory_id' => 10],
                ['name_en' => 'safety car', 'name_pl' => 'samochód bezpieczeństwa', 'subcategory_id' => 10],
                ['name_en' => 'race', 'name_pl' => 'wyścig', 'subcategory_id' => 10],
                ['name_en' => 'qualifications', 'name_pl' => 'kwalifikacje', 'subcategory_id' => 10],
                ['name_en' => 'rally', 'name_pl' => 'rajd', 'subcategory_id' => 10],
                ['name_en' => 'off-road', 'name_pl' => 'wyścig terenowy', 'subcategory_id' => 10],
                ['name_en' => 'racetrack', 'name_pl' => 'tor wyścigowy', 'subcategory_id' => 10],
                ['name_en' => 'special stage', 'name_pl' => 'odcinek specjalny', 'subcategory_id' => 10],
                ['name_en' => 'overtake', 'name_pl' => 'wyprzedzać', 'subcategory_id' => 10],
                ['name_en' => 'art', 'name_pl' => 'plastyka', 'subcategory_id' => 11],
                ['name_en' => 'biology', 'name_pl' => 'biologia', 'subcategory_id' => 11],
                ['name_en' => 'chemistry', 'name_pl' => 'chemia', 'subcategory_id' => 11],
                ['name_en' => 'foreign languages', 'name_pl' => 'języki obce', 'subcategory_id' => 11],
                ['name_en' => 'geography', 'name_pl' => 'geografia', 'subcategory_id' => 11],
                ['name_en' => 'history', 'name_pl' => 'historia', 'subcategory_id' => 11],
                ['name_en' => 'information technology', 'name_pl' => 'informatyka', 'subcategory_id' => 11],
                ['name_en' => 'mathematics', 'name_pl' => 'matematyka', 'subcategory_id' => 11],
                ['name_en' => 'music', 'name_pl' => 'muzyka', 'subcategory_id' => 11],
                ['name_en' => 'physical education', 'name_pl' => 'wychowanie fizyczne (wf)', 'subcategory_id' => 11],
                ['name_en' => 'physics', 'name_pl' => 'fizyka', 'subcategory_id' => 11],
                ['name_en' => 'religious education', 'name_pl' => 'religia', 'subcategory_id' => 11],
                ['name_en' => 'science', 'name_pl' => 'przyroda', 'subcategory_id' => 11],
                ['name_en' => 'social studies', 'name_pl' => 'wiedza o społeczeństwie (wos)', 'subcategory_id' => 11],
                ['name_en' => 'technology', 'name_pl' => 'technika', 'subcategory_id' => 11],
                ['name_en' => 'canteen', 'name_pl' => 'stołówka', 'subcategory_id' => 12],
                ['name_en' => 'classroom', 'name_pl' => 'klasa lekcyjna', 'subcategory_id' => 12],
                ['name_en' => 'common room', 'name_pl' => 'świetlica', 'subcategory_id' => 12],
                ['name_en' => 'computer room', 'name_pl' => 'pracownia komputerowa', 'subcategory_id' => 12],
                ['name_en' => 'corridor', 'name_pl' => 'korytarz', 'subcategory_id' => 12],
                ['name_en' => 'gym', 'name_pl' => 'sala gimnastyczna', 'subcategory_id' => 12],
                ['name_en' => "headmaster's office", 'name_pl' => 'gabinet dyrektora', 'subcategory_id' => 12],
                ['name_en' => 'library', 'name_pl' => 'biblioteka', 'subcategory_id' => 12],
                ['name_en' => 'office', 'name_pl' => 'sekretariat', 'subcategory_id' => 12],
                ['name_en' => 'staffroom', 'name_pl' => 'pokój nauczycielski', 'subcategory_id' => 12],
                ['name_en' => 'classmate', 'name_pl' => 'kolega / koleżanka z klasy', 'subcategory_id' => 13],
                ['name_en' => 'schoolmate', 'name_pl' => 'kolega / koleżanka ze szkoły', 'subcategory_id' => 13],
                ['name_en' => 'student', 'name_pl' => 'student', 'subcategory_id' => 13],
                ['name_en' => 'headmaster', 'name_pl' => 'dyrektor', 'subcategory_id' => 13],
                ['name_en' => 'deputy head', 'name_pl' => 'zastępca dyrektora', 'subcategory_id' => 13],
                ['name_en' => 'teacher', 'name_pl' => 'nauczyciel', 'subcategory_id' => 13],
                ['name_en' => 'teaching staff', 'name_pl' => 'grono pedagogiczne', 'subcategory_id' => 13],
                ['name_en' => 'janitor', 'name_pl' => 'woźny szkolny', 'subcategory_id' => 13],
                ['name_en' => 'crammer', 'name_pl' => 'kujon', 'subcategory_id' => 13],
                ['name_en' => 'pupil', 'name_pl' => 'uczeń (niepełnoletni)', 'subcategory_id' => 13],
                ['name_en' => 'schoolboy', 'name_pl' => 'uczeń', 'subcategory_id' => 13],
                ['name_en' => 'schoolgirl', 'name_pl' => 'uczennica', 'subcategory_id' => 13],
                ['name_en' => 'tutor', 'name_pl' => 'korepetytor', 'subcategory_id' => 13],
                ['name_en' => 'airplane', 'name_pl' => 'samolot', 'subcategory_id' => 14],
                ['name_en' => 'helicopter', 'name_pl' => 'helikopter', 'subcategory_id' => 14],
                ['name_en' => 'rocket', 'name_pl' => 'rakieta', 'subcategory_id' => 14],
                ['name_en' => 'bus', 'name_pl' => 'autobus', 'subcategory_id' => 14],
                ['name_en' => 'coach', 'name_pl' => 'autokar', 'subcategory_id' => 14],
                ['name_en' => 'car', 'name_pl' => 'samochód osobowy', 'subcategory_id' => 14],
                ['name_en' => 'taxi', 'name_pl' => 'taksówka', 'subcategory_id' => 14],
                ['name_en' => 'train', 'name_pl' => 'pociąg', 'subcategory_id' => 14],
                ['name_en' => 'tram', 'name_pl' => 'tramwaj', 'subcategory_id' => 14],
                ['name_en' => 'trolleybus', 'name_pl' => 'trolejbus', 'subcategory_id' => 14],
                ['name_en' => 'bike', 'name_pl' => 'rower', 'subcategory_id' => 14],
                ['name_en' => 'tank', 'name_pl' => 'czołg', 'subcategory_id' => 14],
                ['name_en' => 'truck', 'name_pl' => 'ciężarówka', 'subcategory_id' => 14],
                ['name_en' => 'boat', 'name_pl' => 'łódź', 'subcategory_id' => 14],
                ['name_en' => 'ship', 'name_pl' => 'statek', 'subcategory_id' => 14],
                ['name_en' => 'ferry', 'name_pl' => 'prom', 'subcategory_id' => 14],
                ['name_en' => 'hovercraft', 'name_pl' => 'poduszkowiec', 'subcategory_id' => 14],
                ['name_en' => 'sailboat', 'name_pl' => 'żaglówka', 'subcategory_id' => 14],
                ['name_en' => 'yacht', 'name_pl' => 'jacht', 'subcategory_id' => 14],
                ['name_en' => 'submarine', 'name_pl' => 'łódź podwodna', 'subcategory_id' => 14],
                ['name_en' => 'airport', 'name_pl' => 'lotnisko', 'subcategory_id' => 15],
                ['name_en' => 'airline', 'name_pl' => 'linia lotnicza', 'subcategory_id' => 15],
                ['name_en' => 'arrival', 'name_pl' => 'przylot', 'subcategory_id' => 15],
                ['name_en' => 'departure', 'name_pl' => 'odlot', 'subcategory_id' => 15],
                ['name_en' => 'flight', 'name_pl' => 'lot', 'subcategory_id' => 15],
                ['name_en' => 'flight delayed', 'name_pl' => 'lot opóźniony', 'subcategory_id' => 15],
                ['name_en' => 'cancelled flight', 'name_pl' => 'lot odwołany', 'subcategory_id' => 15],
                ['name_en' => 'destination', 'name_pl' => 'cel podróży', 'subcategory_id' => 15],
                ['name_en' => 'business class', 'name_pl' => 'klasa biznesowa', 'subcategory_id' => 15],
                ['name_en' => 'economy class', 'name_pl' => 'klasa ekonomiczna', 'subcategory_id' => 15],
                ['name_en' => 'cabin crew', 'name_pl' => 'personel pokładowy', 'subcategory_id' => 15],
                ['name_en' => 'flight attendant', 'name_pl' => 'stewardesa', 'subcategory_id' => 15],
                ['name_en' => 'check-in desk', 'name_pl' => 'stanowisko odprawy', 'subcategory_id' => 15],
                ['name_en' => 'emergency landing', 'name_pl' => 'lądowanie awaryjne', 'subcategory_id' => 15],
                ['name_en' => 'stopover', 'name_pl' => 'międzylondowanie', 'subcategory_id' => 15],
                ['name_en' => 'gate', 'name_pl' => 'bramka', 'subcategory_id' => 15],
                ['name_en' => 'security checkpoint', 'name_pl' => 'kontrola bezpieczeństwa', 'subcategory_id' => 15],
                ['name_en' => 'baggage reclaim', 'name_pl' => 'odbiór bagażu', 'subcategory_id' => 15],
                ['name_en' => 'excess baggage', 'name_pl' => 'nadbagaż', 'subcategory_id' => 15],
                ['name_en' => 'terminal', 'name_pl' => 'terminal', 'subcategory_id' => 15],
                ['name_en' => 'duty-free shop', 'name_pl' => 'sklep bezcłowy', 'subcategory_id' => 15],
                ['name_en' => 'ticket', 'name_pl' => 'bilet', 'subcategory_id' => 15],
                ['name_en' => 'window seat', 'name_pl' => 'miejsce przy oknie', 'subcategory_id' => 15],
                ['name_en' => 'cat', 'name_pl' => 'kot', 'subcategory_id' => 16],
                ['name_en' => 'dog', 'name_pl' => 'pies', 'subcategory_id' => 16],
                ['name_en' => 'puppy', 'name_pl' => 'sczeniak', 'subcategory_id' => 16],
                ['name_en' => 'fish', 'name_pl' => 'rybka', 'subcategory_id' => 16],
                ['name_en' => 'guinea pig', 'name_pl' => 'świnka morska', 'subcategory_id' => 16],
                ['name_en' => 'hamster', 'name_pl' => 'chomik', 'subcategory_id' => 16],
                ['name_en' => 'mouse', 'name_pl' => 'mysz', 'subcategory_id' => 16],
                ['name_en' => 'parrot', 'name_pl' => 'papuga', 'subcategory_id' => 16],
                ['name_en' => 'rabbit', 'name_pl' => 'królik', 'subcategory_id' => 16],
                ['name_en' => 'turtle', 'name_pl' => 'żółw', 'subcategory_id' => 16],
                ['name_en' => 'crow', 'name_pl' => 'wrona', 'subcategory_id' => 17],
                ['name_en' => 'crane', 'name_pl' => 'żóraw', 'subcategory_id' => 17],
                ['name_en' => 'pheasant', 'name_pl' => 'bażant', 'subcategory_id' => 17],
                ['name_en' => 'lark', 'name_pl' => 'skowronek', 'subcategory_id' => 17],
                ['name_en' => 'jay', 'name_pl' => 'sójka', 'subcategory_id' => 17],
                ['name_en' => 'magpie', 'name_pl' => 'sroka', 'subcategory_id' => 17],
                ['name_en' => 'nightingale', 'name_pl' => 'słowik', 'subcategory_id' => 17],
                ['name_en' => 'partridge', 'name_pl' => 'kuropatwa', 'subcategory_id' => 17],
                ['name_en' => 'peacock', 'name_pl' => 'paw', 'subcategory_id' => 17],
                ['name_en' => 'pigeon', 'name_pl' => 'gołąb', 'subcategory_id' => 17],
                ['name_en' => 'quail', 'name_pl' => 'przepiórka', 'subcategory_id' => 17],
                ['name_en' => 'raven', 'name_pl' => 'kruk', 'subcategory_id' => 17],
                ['name_en' => 'rook', 'name_pl' => 'gawron', 'subcategory_id' => 17],
                ['name_en' => 'starling', 'name_pl' => 'szpak', 'subcategory_id' => 17],
                ['name_en' => 'stork', 'name_pl' => 'bocian', 'subcategory_id' => 17],
                ['name_en' => 'swallow', 'name_pl' => 'jaskółka', 'subcategory_id' => 17],
                ['name_en' => 'ostrich', 'name_pl' => 'struś', 'subcategory_id' => 17],
                ['name_en' => 'woodpecker', 'name_pl' => 'dzięcioł', 'subcategory_id' => 17],
                ['name_en' => 'anchovy', 'name_pl' => 'sardela', 'subcategory_id' => 18],
                ['name_en' => 'bream', 'name_pl' => 'leszcz', 'subcategory_id' => 18],
                ['name_en' => 'carp', 'name_pl' => 'karp', 'subcategory_id' => 18],
                ['name_en' => 'catfish', 'name_pl' => 'sum', 'subcategory_id' => 18],
                ['name_en' => 'cod', 'name_pl' => 'dorsz', 'subcategory_id' => 18],
                ['name_en' => 'crucian', 'name_pl' => 'karaś', 'subcategory_id' => 18],
                ['name_en' => 'eel', 'name_pl' => 'węgorz', 'subcategory_id' => 18],
                ['name_en' => 'flounder', 'name_pl' => 'flądra', 'subcategory_id' => 18],
                ['name_en' => 'hake', 'name_pl' => 'morszczuk', 'subcategory_id' => 18],
                ['name_en' => 'halibut', 'name_pl' => 'halibut', 'subcategory_id' => 18],
                ['name_en' => 'herring', 'name_pl' => 'śledź', 'subcategory_id' => 18],
                ['name_en' => 'mackerel', 'name_pl' => 'makrela', 'subcategory_id' => 18],
                ['name_en' => 'perch', 'name_pl' => 'okoń', 'subcategory_id' => 18],
                ['name_en' => 'pike', 'name_pl' => 'szczupak', 'subcategory_id' => 18],
                ['name_en' => 'piranha', 'name_pl' => 'pirania', 'subcategory_id' => 18],
                ['name_en' => 'roach', 'name_pl' => 'płotka', 'subcategory_id' => 18],
                ['name_en' => 'salmon', 'name_pl' => 'łosoś', 'subcategory_id' => 18],
                ['name_en' => 'sardine', 'name_pl' => 'sardynka', 'subcategory_id' => 18],
                ['name_en' => 'shark', 'name_pl' => 'rekin', 'subcategory_id' => 18],
                ['name_en' => 'sturgeon', 'name_pl' => 'jesiotr', 'subcategory_id' => 18],
                ['name_en' => 'trout', 'name_pl' => 'pstrąg', 'subcategory_id' => 18],
                ['name_en' => 'tuna', 'name_pl' => 'tuńczyk', 'subcategory_id' => 18]
            ]
        );
    }
}
